imports = {
    'typing': ['Optional', 'List', 'Union'],
    'vkbottle_types.objects': [
            'GroupsGroupFull',
            'GroupsGroup',
            'MessagesMessage',
            'MessagesPinnedMessage',
            'MessagesHistoryAttachment',
            'MessagesChatFull',
            'MessageChatPreview',
            'MessagesLongpollParams',
            'MessagesLastActivity',
            'MessagesConversation',
            'BaseMessageError',
            'MessagesConversationWithMessage',
            'BaseBoolInt',
            'MessagesChatRestrictions',
            'MessagesChat',
            'UsersUser',
            'UsersUserFull',
            'MessagesLongpollMessages',
            'MessagesConversationMember',
        ],
    '.base_response': ['BaseResponse']
}